#
# This file is used by the aws-eks-verify workflow
# The values here are used by the Probr runtime
# to customize the tests that are executed.
#
# As of Nov 2021, the only pack suitable for our
# EKS validation is the Kubernetes-CIS service pack
# https://github.com/probr/probr-pack-kubernetes
#
Run:
  - "kubernetes"
ServicePacks:
  Kubernetes:
    AuthorisedContainerImage: "citihub/probr-probe"
    UnauthorisedContainerImage: "fixme/bad-image-name"
