---
name: terraform validate

inputs:
  working-directory:
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform -chdir=${{ inputs.working-directory }} init
      shell: bash

    - name: Terraform Format
      run: terraform -chdir=${{ inputs.working-directory }} fmt -check
        -recursive
      shell: bash

    - name: Terraform Validate
      run: terraform -chdir=${{ inputs.working-directory }} validate
      shell: bash
