---
name: terraform validate

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init
      shell: bash

    - name: Terraform Format
      run: terraform fmt -check
        -recursive
      shell: bash

    - name: Terraform Validate
      run: terraform validate
      shell: bash
